-- Tutorial setup stuff, ignore if using other data
USE ROLE ACCOUNTADMIN;
GRANT CREATE VIEW ON SCHEMA CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES TO ROLE ACCOUNTADMIN;
GRANT CREATE SEMANTIC VIEW ON SCHEMA CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES TO ROLE ACCOUNTADMIN;



-- Grant permissions to your target role (Replace SYSADMIN if you use a custom role)
GRANT USAGE ON DATABASE CORTEX_ANALYST_DEMO TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES TO ROLE ACCOUNTADMIN;

-- Allow creating tables (for the repo) and views (for the semantic models)
GRANT CREATE TABLE ON SCHEMA CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES TO ROLE ACCOUNTADMIN;
GRANT CREATE VIEW ON SCHEMA CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES TO ROLE ACCOUNTADMIN;

-- 4. (Optional) If you are using a specific Cortex Role instead of SYSADMIN:
-- GRANT CREATE TABLE ON SCHEMA CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES TO ROLE CORTEX_USER_ROLE;

-- Create Central Table

CREATE TABLE IF NOT EXISTS CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES.SEMANTIC_ATTRIBUTE_REPOSITORY (
    ATTRIBUTE_NAME STRING,       -- The column name (e.g., 'TOTAL_REVENUE')
    DESCRIPTION STRING,          -- Validated description
    SYNONYMS VARIANT,            -- Array of synonyms (e.g., ['Sales', 'Income'])
    SAMPLE_VALUES STRING,        -- Optional: validated sample values
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ATTRIBUTE_NAME)
);